title: "Zeina Bourhane, PhD"
description: Microbial ecology | Metagenomics | Metabolomics | Bioinformatics | Extreme environments
theme: minima

author:
name: Zeina Bourhane, PhD
##  email: zeina.bourhane@univ-pau.fr

header_pages:
  - publications.md
  - conferences.md
  - funding.md
  - awards.md
  - teaching.md
  - outreach.md
 ## - media.md
  - courses.md
  - cv.md

show_excerpts: true
