title: "Zeina Bourhane, PhD"
description: Economist | Development | Agricultural | Environmental Economics
theme: minima

author:
  name: Zeina Bourhane, PhD
  email: m.ayaz@univ-pau.fr

header_pages:
  - publications.md
  - conferences.md
  - research.md
  - teaching.md
  - awards.md
  - cv.md

show_excerpts: true
